### ISSUE TITLE
Invalid `salesElementType` value in endpoint example SellerLogtimesNew.json 

### ISSUE THREAD

**Issue by Untit1ed** [tip-initiative/tip-initiative-apis#132]
`SellerLogtimesNew.json` endpoint examples (both 5.0 and WIP) currently have invalid `units.salesElement.salesElementType` values `"Program Based"`. 
https://github.com/tip-initiative/tip-initiative-apis/blob/ddf1cbe416181c6d7780256383f7fb4b509af1ce/endpoints/examples/WIP-Examples/SellerLogtimesNew.json#L53

According to `commonSchemas.yaml`, the only allowed values are Time-specific, Program and Audience.
https://github.com/tip-initiative/tip-initiative-apis/blob/46acfe8b417cb9200107062c7ecb6ebead082c83/endpoints/schemas/commonSchemas.yaml#L841

**Comment by touficmoubarak** [comment]
All occurrences are updated. thanks for reviewing. including makegood, invoice, and others.
