### ISSUE TITLE
CalendarDateTime description

### ISSUE THREAD

**Issue by Untit1ed** [tip-initiative/tip-initiative-apis#143]
The wording seems to be misleading on `DateTime`'s `calendarDateTime` field description in [commonSchemas.yaml](https://github.com/tip-initiative/tip-initiative-apis/blob/22b532e0041015f2fe359f3a501dc965900ffeae/endpoints/schemas/commonSchemas.yaml)
```
calendarDateTime:
          description: >-
            The calendar date and time on which the unit aired/scheduled. Time is interpreted based on
            the local timezone of the mediaoutlet using military date time YYYY-MM-DDTHH:MM:SS
          type: string
          format: date-time
```
Military date time format is usually DDHHMM(Z)MONYY. 
Was "ISO 8601" supposed to be used there instead of "military date time"?

**Comment by touficmoubarak** [comment]
You're correct,  the wording is misleading.  Date time must conform to iso 8601. Description will be fixed
