### ISSUE TITLE
Feature Request: Competitive Endpoint for Political Order Summaries

### ISSUE THREAD

**Issue by mcoirad-gmmb** [tip-initiative/tip-initiative-apis#150]
On the political side of TV and Radio buying, stations and station groups send out tons of manually formatted/collated emails containing summaries on each day's political ad buys. Some have already been starting to create their own automated solutions to this problem. (sometimes really just automating the sending of emails, but some also are looking into specific JSON payloads that can be sent to API endpoints) Would it be possible to make this an official part of the TIP Initiative? Or if it already has been, if that's on the roadmap for a future version of TIP?

Happy to make pull request to the develop branch with an example endpoint/schema if that would help get things started.

**Comment by touficmoubarak** [comment]
I appreciate if you Fork Develop and create your own branch. I am very excited to learn more about this area of interest.

**Comment by mcoirad-gmmb** [comment]
Thank you, I am discussing this with different stations and will add a branch with a demo schema shortly.

**Comment by touficmoubarak** [comment]
> Thank you, I am discussing this with different stations and will add a branch with a demo schema shortly.

Just to understand,  is this more like a logtimes filtered to political spots or more.  I know of regulations to provide equivalent exposure to all parties, is that we are talking about? Does it also, include pricing, etc.

Looking forward to learn more.

**Comment by mcoirad-gmmb** [comment]
Nope, I don't think that political competitive data is legally required to distributed (although stations are required to post what political ads are running to the FCC, and there are a bunch of rules on political ad sales). But the political competitive data is sort of similar to log times, but more of a summary of the buy rather than the details.

**Comment by touficmoubarak** [comment]
I will stay tuned in to learn more of your discussions with the stations and your decision.  At the same time,  James might want to raise that question to the larger group of contributors and gather their input as well.

**Comment by mcoirad-gmmb** [comment]
I think that would also help, happy to jump on a call to discuss things too if that would help.

**Comment by jamessouthern** [comment]
> On the political side of TV and Radio buying, stations and station groups send out tons of manually formatted/collated emails containing summaries on each day's political ad buys. Some have already been starting to create their own automated solutions to this problem. (sometimes really just automating the sending of emails, but some also are looking into specific JSON payloads that can be sent to API endpoints) Would it be possible to make this an official part of the TIP Initiative? Or if it already has been, if that's on the roadmap for a future version of TIP?
> 
> Happy to make pull request to the develop branch with an example endpoint/schema if that would help get things started.

Thanks for the explanation mcoirad. The sell-side vendors did not recall this as an issue but I can see that it would probably apply more to the sales team at this point who manually generate the reports and emails. Lets go ahead and draft this as it sounds valuable to put something out at this time. Our normal process would be to add it to the Google Sheets, review with the team and then build API. Could we get on a call and help us build the Google Sheet next week?  Ping me at james@frontrowadvisory.com

**Comment by mcoirad-gmmb** [comment]
Sent you a message by email, following up here. Definitely would be happy to arrange a time to meet.

**Comment by touficmoubarak** [comment]
Implementation is adopted for 6.1.0
