### ISSUE TITLE
Possible to standardize capitalization on objects and schemas?

### ISSUE THREAD

**Issue by mcoirad-gmmb** [tip-initiative/tip-initiative-apis#25]
Especially for fields that contain "ID"/"Id", some more consistency would be helpful for coordinating the implementation process between buyers and sellers.

Unless there is already a method to the current system, which I may have overlooked.

**Comment by jamessouthern** [comment]
Thanks for your comment. We do have a standard but do miss some typos. 
We have a style validator coming online that should catch them.
