### ISSUE TITLE
Should media/object be changed to inventoryTypes per Framework 4.0?

### ISSUE THREAD

**Issue by jamessouthern** [tip-initiative/tip-initiative-apis#30]
![Capture](https://user-images.githubusercontent.com/51486706/67532278-afb4d500-f693-11e9-95a7-c3067aeca8fd.JPG)

https://github.com/tip-initiative/tip-initiative-apis/blob/959a77671795101472913bf3f1641769f75d7bf7/endpoints/schemas/commercialInstructionSchemas.yaml#L88

instructionDetail | Array Header | Array of Objects | Commercial Instruction details for each instruction type
-- | -- | -- | --
actionType | Required | Enum | "New" "Revised" "Cancelled"
inventoryTypes | Optional | Array<Enum> | Valid Inventory Types for the instructions "Commercial"  "Makegood" "Bonus" "ADU" "Bookends" "Piggybacks" "Sponsorship" "Donut" "Sandwich" "Billboard" "<Custom>"

**Comment by touficmoubarak** [comment]
Should linkType match as well the inventory type list?

Sent from Mail for Windows 10

From: jamessouthern
Sent: Thursday, October 24, 2019 6:23 PM
To: tip-initiative/tip-initiative-apis
Cc: Subscribed
Subject: [tip-initiative/tip-initiative-apis] Should media/object be changedto inventoryTypes per Framework 4.0? (#30)


https://github.com/tip-initiative/tip-initiative-apis/blob/959a77671795101472913bf3f1641769f75d7bf7/endpoints/schemas/commercialInstructionSchemas.yaml#L88
instructionDetail
Array Header
Array of Objects
Commercial Instruction details for each instruction type
actionType
Required
Enum
"New" "Revised" "Cancelled"
inventoryTypes
Optional
Array
Valid Inventory Types for the instructions "Commercial" "Makegood" "Bonus" "ADU" "Bookends" "Piggybacks" "Sponsorship" "Donut" "Sandwich" "Billboard" ""
