### ISSUE TITLE
PDFs not attached to V1.0.0 release

### ISSUE THREAD

**Issue by mcoirad-gmmb** [tip-initiative/tip-initiative-apis#99]
https://github.com/tip-initiative/tip-initiative-apis/releases/tag/V1.0.0
(unless they are downloadable from somewhere else that I missed)

Am I correct to assume the V1.0.0 release matches the framework version 4.0.0 for the invoice and logtimes endpoints?

**Comment by touficmoubarak** [comment]
Just got Added. they are the same files on RC1.0.0-alpha.

**Comment by mcoirad-gmmb** [comment]
Thank you very much!
